name: CMake

on:
  push:
    branches: [ edge ]
  pull_request:
    branches: [ edge ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir stardust-celeste-ubuntu
          cd stardust-celeste-ubuntu
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          cp ../LICENSE ./
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Linux
          path: |
            stardust-celeste-ubuntu
            README.md

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -D-DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Windows
          path: |
            Release
            LICENSE
            README.md

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add cmake gmp mpc1 mpfr4 make
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir stardust-celeste-psp
          cd stardust-celeste-psp
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
          cp ../LICENSE ./
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-PSP
          path: |
            stardust-celeste-psp
            README.md
