name: Stardust

on:
  push:
    branches: [ edge ]
  pull_request:
    branches: [ edge ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          make test
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Linux
          path: |
            build/libStardust-Celeste.a
            LICENSE
            README.md

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
          cmake --build . --config Release --target RUN_TESTS
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Windows
          path: |
            Release\Stardust-Celeste.lib
            LICENSE
            README.md

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add bash cmake gmp mpc1 mpfr4 make
      
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Install PPSSPP Headless
        run: |
          wget https://github.com/Iridescence-Technologies/PPSSPP-Headless/raw/edge/ppsspp_headless.tar.xz
          tar -xvf ppsspp_headless.tar.xz -C ./
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
          cd ..
          chmod +x test_runner_psp.sh
          bash test_runner_psp.sh
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-PSP
          path: |
            build/libStardust-Celeste.a
            LICENSE
            README.md
